"""grading: code review submissions and peer reviews

Revision ID: 40486c1afd58
Revises: c5086785d15b
Create Date: 2026-09-15 09:48:35.227561
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40486c1afd58'
down_revision: Union[str, None] = 'c5086785d15b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_review_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('language', sa.String(length=24), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('auto_report', sa.JSON(), nullable=False),
    sa.Column('auto_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('review_goal', sa.Integer(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('code_review_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_code_review_submissions_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_review_submissions_status'), ['status'], unique=False)

    op.create_table('peer_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('correctness', sa.Integer(), nullable=False),
    sa.Column('readability', sa.Integer(), nullable=False),
    sa.Column('efficiency', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['code_review_submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'reviewer_id', name='uq_review_once')
    )
    with op.batch_alter_table('peer_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_peer_reviews_reviewer_id'), ['reviewer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_peer_reviews_submission_id'), ['submission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peer_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_peer_reviews_submission_id'))
        batch_op.drop_index(batch_op.f('ix_peer_reviews_reviewer_id'))

    op.drop_table('peer_reviews')
    with op.batch_alter_table('code_review_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_review_submissions_status'))
        batch_op.drop_index(batch_op.f('ix_code_review_submissions_author_id'))

    op.drop_table('code_review_submissions')
    # ### end Alembic commands ###
